/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'social' : IDL.Null,
  'viral' : IDL.Null,
  'trending' : IDL.Null,
  'politics' : IDL.Null,
});
export const ArticleId = IDL.Nat;
export const NewsArticle = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'source' : IDL.Text,
  'summary' : IDL.Text,
  'shareCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'category' : Category,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNewsArticle' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Text],
      [ArticleId],
      [],
    ),
  'deleteNewsArticle' : IDL.Func([ArticleId], [], []),
  'getArticlesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNewsArticle' : IDL.Func([ArticleId], [NewsArticle], ['query']),
  'getPaginatedArticles' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shareNewsArticle' : IDL.Func([ArticleId], [], []),
  'updateNewsArticle' : IDL.Func(
      [ArticleId, IDL.Text, IDL.Text, Category, IDL.Text],
      [NewsArticle],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'social' : IDL.Null,
    'viral' : IDL.Null,
    'trending' : IDL.Null,
    'politics' : IDL.Null,
  });
  const ArticleId = IDL.Nat;
  const NewsArticle = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'source' : IDL.Text,
    'summary' : IDL.Text,
    'shareCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'category' : Category,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNewsArticle' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Text],
        [ArticleId],
        [],
      ),
    'deleteNewsArticle' : IDL.Func([ArticleId], [], []),
    'getArticlesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNewsArticle' : IDL.Func([ArticleId], [NewsArticle], ['query']),
    'getPaginatedArticles' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shareNewsArticle' : IDL.Func([ArticleId], [], []),
    'updateNewsArticle' : IDL.Func(
        [ArticleId, IDL.Text, IDL.Text, Category, IDL.Text],
        [NewsArticle],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };