/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ArticleId = bigint;
export type Category = { 'social' : null } |
  { 'viral' : null } |
  { 'trending' : null } |
  { 'politics' : null };
export interface NewsArticle {
  'id' : ArticleId,
  'title' : string,
  'creator' : Principal,
  'source' : string,
  'summary' : string,
  'shareCount' : bigint,
  'timestamp' : bigint,
  'category' : Category,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNewsArticle' : ActorMethod<
    [string, string, Category, string],
    ArticleId
  >,
  'deleteNewsArticle' : ActorMethod<[ArticleId], undefined>,
  'getArticlesByCategory' : ActorMethod<[Category], Array<NewsArticle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNewsArticle' : ActorMethod<[ArticleId], NewsArticle>,
  'getPaginatedArticles' : ActorMethod<[bigint], Array<NewsArticle>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'shareNewsArticle' : ActorMethod<[ArticleId], undefined>,
  'updateNewsArticle' : ActorMethod<
    [ArticleId, string, string, Category, string],
    NewsArticle
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];